### ISSUE TITLE
Make the decoder open file from the sound directory by default

### ISSUE THREAD

**Issue by araghon007** [yobson1/glua-soundduration#2]
I'd suggest prepending soundPath with "sound/" when opening the file so NewSoundDuration could be used as a drop in replacement for SoundDuration (e.g. NewSoundDuration("test.wav") instead of NewSoundDuration("sound/test.wav"))

**Comment by yobson1** [comment]
I think it's preferable to leave it as is so sound files from any directory can be accessed with NewSoundDuration, sounds downloaded to the data directory for example. If your use case doesn't require that then you're free to make the change for yourself.
